-- ============================================================================
-- Migration: Blog Automation Settings
-- Version: 012
-- Description: Creates table for blog article automation settings
-- Date: January 2025
-- ============================================================================

-- ============================================================================
-- 1. CREATE BLOG_AUTOMATION_SETTINGS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS blog_automation_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  is_enabled BOOLEAN DEFAULT false,
  interval_hours INTEGER DEFAULT 24,
  last_run_at TIMESTAMP WITH TIME ZONE,
  next_run_at TIMESTAMP WITH TIME ZONE,
  total_articles_generated INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES users(id),
  -- Only one row allowed
  CONSTRAINT single_row CHECK (id = '00000000-0000-0000-0000-000000000001'::uuid)
);

-- Insert default settings row
INSERT INTO blog_automation_settings (id, is_enabled, interval_hours, last_run_at, next_run_at)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, false, 24, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_blog_automation_enabled ON blog_automation_settings(is_enabled) WHERE is_enabled = true;
CREATE INDEX IF NOT EXISTS idx_blog_automation_next_run ON blog_automation_settings(next_run_at) WHERE is_enabled = true;

-- Add RLS policies
ALTER TABLE blog_automation_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read (for cron job)
CREATE POLICY "Allow public read for automation settings"
  ON blog_automation_settings
  FOR SELECT
  USING (true);

-- Allow authenticated users to update
CREATE POLICY "Allow authenticated users to update automation settings"
  ON blog_automation_settings
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- Add comment
COMMENT ON TABLE blog_automation_settings IS 'Stores settings for automated blog article generation';
COMMENT ON COLUMN blog_automation_settings.is_enabled IS 'Whether automation is enabled';
COMMENT ON COLUMN blog_automation_settings.interval_hours IS 'Interval in hours between article generations (default: 24)';
COMMENT ON COLUMN blog_automation_settings.last_run_at IS 'Timestamp of last automation run';
COMMENT ON COLUMN blog_automation_settings.next_run_at IS 'Timestamp of next scheduled run';
COMMENT ON COLUMN blog_automation_settings.total_articles_generated IS 'Total number of articles generated by automation';

